name: integration
concurrency: integration

on:
  push:
    branches:
      # Run on every push to trunk
      - trunk
  schedule:
    # Run every Saturday at 4:05 AM UTC
    - cron: "5 4 * * SAT"

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: base
            sync-args: ""
          - name: lxml
            sync-args: "--extra lxml"
    name: End-to-end tests (${{ matrix.name }})
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.14"

      - name: Sync runtime environment
        run: uv sync --frozen --no-dev ${{ matrix.sync-args }}

      - name: Create csv
        run: uv run --frozen --no-dev mtg-ssm create collection1.csv

      - name: Update csv
        run: uv run --frozen --no-dev mtg-ssm update collection1.csv

      - name: Create xlsx
        run: uv run --frozen --no-dev mtg-ssm create collection2.xlsx

      - name: Update xlsx
        run: uv run --frozen --no-dev mtg-ssm update collection2.xlsx

      - name: Merge csv and xlsx
        run: uv run --frozen --no-dev mtg-ssm merge collection3.xlsx collection1.csv collection2.xlsx
