name: lint

on:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run all pre-commit checks
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.14"

      - run: uv sync --frozen

      - run: uv run --frozen pre-commit run --all-files
