name: publish
concurrency: publish

on:
  push:
    branches:
      - trunk
    tags:
      - "**"

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          # setuptools_scm needs the git history
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.14"

      - name: Build a binary wheel and a source tarball
        run: uv build --sdist --wheel --out-dir dist

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
