name: pytest

on:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  can-run:
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Can run on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: Sync runtime environment
        run: uv sync --frozen --no-dev

      - name: Run mtg-ssm
        run: uv run --frozen --no-dev mtg-ssm --help

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    name: Python ${{ matrix.python-version }} pytest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: Sync test environment
        run: uv sync --frozen --extra lxml

      - name: Execute pytest
        run: uv run --frozen pytest tests/

      - name: Convert coverage
        run: uv run --frozen coverage lcov

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2.3.8
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: python-${{ matrix.python-version }}
          path-to-lcov: coverage.lcov
          parallel: true

  finish:
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.3.8
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
